export type CategoryId =
  | 'cases'
  | 'protection'
  | 'charging'
  | 'power'
  | 'audio'
  | 'loadshedding'
  | 'gaming'
  | 'car'

export interface Category {
  id: CategoryId
  index: string
  name: string
  blurb: string
  range: string
  image: string
}

export interface Product {
  id: string
  name: string
  brand: string
  category: CategoryId
  price: number
  was?: number
  rating: number
  reviews: number
  sold: number
  image: string
  badge?: 'Best seller' | 'Bundle' | 'Grid-free' | 'New' | 'Low stock'
  compat: string
  /** Device models this fits. ['*'] means universal. */
  fits: string[]
  blurb: string
  features: string[]
  spec: [string, string][]
  variants?: { label: string; options: string[] }
  stock: number
}

export interface Brand {
  id: string
  name: string
  models: string[]
}

export const deviceBrands: Brand[] = [
  {
    id: 'samsung',
    name: 'Samsung',
    models: [
      'Galaxy A14', 'Galaxy A24', 'Galaxy A34', 'Galaxy A54',
      'Galaxy S22', 'Galaxy S23', 'Galaxy S23 Ultra', 'Galaxy S24',
    ],
  },
  {
    id: 'apple',
    name: 'Apple',
    models: [
      'iPhone 12', 'iPhone 13', 'iPhone 14', 'iPhone 14 Pro',
      'iPhone 15', 'iPhone 15 Pro', 'iPhone 16 Pro',
    ],
  },
  {
    id: 'xiaomi',
    name: 'Xiaomi',
    models: ['Redmi 12C', 'Redmi Note 12', 'Redmi Note 13', 'Poco X6'],
  },
  {
    id: 'huawei',
    name: 'Huawei',
    models: ['Nova 11', 'P40 Lite', 'Y9 Prime'],
  },
  {
    id: 'oppo',
    name: 'Oppo',
    models: ['Oppo A78', 'Reno 8T'],
  },
  {
    id: 'other',
    name: 'Other / not listed',
    models: ['Universal fit'],
  },
]

export const categories: Category[] = [
  {
    id: 'cases',
    index: '01',
    name: 'Cases & Covers',
    blurb: 'Drop-tested shells for Samsung, iPhone and Xiaomi.',
    range: 'R120–R350',
    image: '/images/cases.jpg',
  },
  {
    id: 'protection',
    index: '02',
    name: 'Screen Protection',
    blurb: '9H tempered glass, privacy film and lens guards.',
    range: 'R80–R200',
    image: '/images/protector.jpg',
  },
  {
    id: 'charging',
    index: '03',
    name: 'Cables & Chargers',
    blurb: 'Braided leads and fast bricks that survive daily abuse.',
    range: 'R100–R250',
    image: '/images/cable.jpg',
  },
  {
    id: 'power',
    index: '04',
    name: 'Power Banks',
    blurb: '5 000–20 000mAh packs sized for a four-hour block.',
    range: 'R199–R450',
    image: '/images/powerbank.jpg',
  },
  {
    id: 'audio',
    index: '05',
    name: 'Audio & Earbuds',
    blurb: 'Budget TWS with ENC mics and real battery life.',
    range: 'R250–R500',
    image: '/images/earbuds.jpg',
  },
  {
    id: 'loadshedding',
    index: '06',
    name: 'Grid-Free Light',
    blurb: 'Rechargeable bulbs and work lights that outlast the schedule.',
    range: 'R150–R500',
    image: '/images/light.jpg',
  },
  {
    id: 'gaming',
    index: '07',
    name: 'Mobile Gaming',
    blurb: 'Triggers, grips and coolers — all under R200.',
    range: 'R99–R200',
    image: '/images/gaming.jpg',
  },
  {
    id: 'car',
    index: '08',
    name: 'Mounts & Stands',
    blurb: 'Vent clips, dash suction and folding aluminium.',
    range: 'R120–R250',
    image: '/images/carmount.jpg',
  },
]

export const products: Product[] = [
  {
    id: 'armour-grip-a-series',
    name: 'Armour Grip Rugged Case',
    brand: 'Goods2Hoods',
    category: 'cases',
    price: 149,
    was: 199,
    rating: 4.6,
    reviews: 1284,
    sold: 3120,
    image: '/images/cases.jpg',
    badge: 'Best seller',
    compat: 'Samsung A-series',
    fits: ['Galaxy A14', 'Galaxy A24', 'Galaxy A34', 'Galaxy A54'],
    blurb:
      'Shock-absorbing TPU frame with a raised camera lip and grip ridges that stay put in a back pocket.',
    features: [
      '1.8m drop-tested corners',
      'Raised 1.2mm camera lip',
      'Anti-slip side ridges',
      'Wireless-charge friendly',
    ],
    spec: [
      ['Material', 'TPU + PC hybrid'],
      ['Drop rating', '1.8m onto concrete'],
      ['Thickness', '2.1mm'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Device', options: ['Galaxy A14', 'Galaxy A24', 'Galaxy A34', 'Galaxy A54'] },
    stock: 64,
  },
  {
    id: 'clearshield-iphone',
    name: 'ClearShield Anti-Yellow Case',
    brand: 'Goods2Hoods',
    category: 'cases',
    price: 179,
    rating: 4.5,
    reviews: 842,
    sold: 2210,
    image: '/images/cases.jpg',
    compat: 'iPhone 13–15',
    fits: ['iPhone 13', 'iPhone 14', 'iPhone 15', 'iPhone 15 Pro'],
    blurb:
      'Optically clear back that resists the yellowing every cheap case suffers by month three.',
    features: [
      'UV-stable acrylic back',
      'Air-cushion corners',
      'Precise button click',
      '2-year clarity promise',
    ],
    spec: [
      ['Material', 'Acrylic back + TPU bumper'],
      ['Clarity', 'UV-stable, 2-year promise'],
      ['Thickness', '1.9mm'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Device', options: ['iPhone 13', 'iPhone 14', 'iPhone 15', 'iPhone 15 Pro'] },
    stock: 48,
  },
  {
    id: 'kasi-camo-case',
    name: 'Kasi Camo Rugged Case',
    brand: 'Street Series',
    category: 'cases',
    price: 129,
    rating: 4.3,
    reviews: 517,
    sold: 1460,
    image: '/images/cases.jpg',
    compat: 'Redmi Note series',
    fits: ['Redmi Note 12', 'Redmi Note 13', 'Redmi 12C'],
    blurb: 'Matte camo shell built for dust, sweat and the daily commute.',
    features: ['Matte anti-fingerprint finish', 'Dust-plug charging port', 'Textured grip panels'],
    spec: [
      ['Material', 'Matte TPU'],
      ['Port cover', 'Integrated dust plug'],
      ['Thickness', '2.4mm'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Device', options: ['Redmi Note 12', 'Redmi Note 13', 'Redmi 12C'] },
    stock: 31,
  },
  {
    id: 'maglock-slim',
    name: 'MagLock Slim Magnetic Case',
    brand: 'Goods2Hoods',
    category: 'cases',
    price: 329,
    was: 399,
    rating: 4.7,
    reviews: 396,
    sold: 880,
    image: '/images/cases.jpg',
    badge: 'New',
    compat: 'iPhone Pro, MagSafe',
    fits: ['iPhone 14 Pro', 'iPhone 15 Pro', 'iPhone 16 Pro'],
    blurb: 'Ring-magnet array that locks onto car mounts and wireless pucks without a shim.',
    features: ['18-magnet N52 ring', '15W MagSafe pass-through', 'Soft-touch coating'],
    spec: [
      ['Magnets', '18 x N52 ring array'],
      ['Wireless', '15W pass-through'],
      ['Finish', 'Soft-touch matte'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Device', options: ['iPhone 14 Pro', 'iPhone 15 Pro', 'iPhone 16 Pro'] },
    stock: 22,
  },
  {
    id: 'case-glass-bundle',
    name: 'Case + Glass Bundle',
    brand: 'Goods2Hoods',
    category: 'cases',
    price: 249,
    was: 338,
    rating: 4.8,
    reviews: 2043,
    sold: 4870,
    image: '/images/cases.jpg',
    badge: 'Bundle',
    compat: 'Samsung & iPhone',
    fits: ['Galaxy A54', 'Galaxy S23', 'iPhone 13', 'iPhone 15'],
    blurb:
      'The pairing that outsells standalone cases 2.3 to 1: rugged shell plus two sheets of 9H glass.',
    features: [
      'Armour Grip case included',
      'Two tempered glass sheets',
      'Alignment tray and wipes',
      'Save R89 against buying apart',
    ],
    spec: [
      ['Contents', 'Case + 2x glass + tray'],
      ['Saving', 'R89'],
      ['Ships as', 'One parcel'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Device', options: ['Galaxy A54', 'Galaxy S23', 'iPhone 13', 'iPhone 15'] },
    stock: 76,
  },
  {
    id: 'glass-2pack',
    name: '9H Tempered Glass (2-pack)',
    brand: 'Goods2Hoods',
    category: 'protection',
    price: 89,
    was: 129,
    rating: 4.6,
    reviews: 5310,
    sold: 8940,
    image: '/images/protector.jpg',
    badge: 'Best seller',
    compat: 'Most Samsung, iPhone & Xiaomi',
    fits: [
      'Galaxy A34', 'Galaxy A54', 'Galaxy S23', 'iPhone 13',
      'iPhone 14', 'iPhone 15', 'Redmi Note 13',
    ],
    blurb:
      'Two sheets, one alignment tray, zero bubbles. The cheapest insurance your screen will ever get.',
    features: [
      '9H surface hardness',
      'Oleophobic coating',
      'Case-friendly 2.5D edge',
      'Alignment tray included',
    ],
    spec: [
      ['Hardness', '9H'],
      ['Edge', '2.5D case-friendly'],
      ['In box', '2 sheets + tray + wipes'],
      ['Warranty', '12 months'],
    ],
    variants: {
      label: 'Device',
      options: ['Galaxy A54', 'Galaxy S23', 'iPhone 13', 'iPhone 15', 'Redmi Note 13'],
    },
    stock: 210,
  },
  {
    id: 'privacy-glass',
    name: 'Anti-Spy Privacy Glass',
    brand: 'Goods2Hoods',
    category: 'protection',
    price: 159,
    rating: 4.4,
    reviews: 1122,
    sold: 2640,
    image: '/images/protector.jpg',
    compat: 'Samsung & iPhone',
    fits: ['Galaxy A54', 'Galaxy S23', 'iPhone 14', 'iPhone 15'],
    blurb: 'A 28-degree viewing angle, so the person next to you on the Gautrain sees nothing.',
    features: ['28° privacy filter', 'Fingerprint-unlock compatible', 'Scratch-resistant 9H face'],
    spec: [
      ['Privacy angle', '28 degrees'],
      ['Hardness', '9H'],
      ['Sensor', 'Fingerprint compatible'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Device', options: ['Galaxy A54', 'Galaxy S23', 'iPhone 14', 'iPhone 15'] },
    stock: 58,
  },
  {
    id: 'curved-glass',
    name: 'Full-Cover Curved Glass',
    brand: 'Goods2Hoods',
    category: 'protection',
    price: 199,
    rating: 4.5,
    reviews: 688,
    sold: 1490,
    image: '/images/protector.jpg',
    compat: 'Galaxy Ultra series',
    fits: ['Galaxy S22', 'Galaxy S23 Ultra', 'Galaxy S24'],
    blurb: 'Edge-to-edge adhesive for curved Ultra displays — no floating halo at the corners.',
    features: ['Full-face adhesive', 'Ultrasonic sensor calibrated', 'Applicator included'],
    spec: [
      ['Adhesive', 'Full-face'],
      ['Sensor', 'Ultrasonic calibrated'],
      ['In box', '1 sheet + applicator'],
      ['Warranty', '12 months'],
    ],
    stock: 27,
  },
  {
    id: 'lens-guard',
    name: 'Camera Lens Guard (3-pack)',
    brand: 'Goods2Hoods',
    category: 'protection',
    price: 99,
    rating: 4.2,
    reviews: 402,
    sold: 1180,
    image: '/images/protector.jpg',
    compat: 'iPhone & Galaxy arrays',
    fits: ['iPhone 14 Pro', 'iPhone 15 Pro', 'iPhone 16 Pro', 'Galaxy S23 Ultra'],
    blurb: 'Three sets of tempered rings that take the scratch instead of your lens.',
    features: ['0.2mm ultra-thin', 'No flare or glare', 'Aluminium bezel'],
    spec: [
      ['Thickness', '0.2mm'],
      ['Bezel', 'Anodised aluminium'],
      ['In box', '3 sets'],
      ['Warranty', '12 months'],
    ],
    stock: 92,
  },
  {
    id: 'cable-3in1',
    name: '3-in-1 Fast Charge Cable',
    brand: 'Goods2Hoods',
    category: 'charging',
    price: 139,
    was: 179,
    rating: 4.5,
    reviews: 3908,
    sold: 6720,
    image: '/images/cable.jpg',
    badge: 'Best seller',
    compat: 'USB-C, Lightning, Micro-USB',
    fits: ['*'],
    blurb: 'One braided cable for every device in the house, the taxi or the office drawer.',
    features: ['1.2m nylon braid', '3A fast charge', '10 000-bend tested', 'Magnetic cable tie'],
    spec: [
      ['Length', '1.2m'],
      ['Current', '3A'],
      ['Tips', 'USB-C / Lightning / Micro'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Colour', options: ['Charcoal', 'Sand', 'Ember'] },
    stock: 143,
  },
  {
    id: 'cable-usbc-60w',
    name: 'Braided USB-C 60W Cable',
    brand: 'Goods2Hoods',
    category: 'charging',
    price: 119,
    rating: 4.6,
    reviews: 1560,
    sold: 3010,
    image: '/images/cable.jpg',
    compat: 'USB-C to USB-C',
    fits: ['*'],
    blurb: 'Two metres of reach, so you can still use the phone while it charges behind the couch.',
    features: ['60W PD e-marker', '480Mbps data', 'Reinforced strain relief'],
    spec: [
      ['Power', '60W PD'],
      ['Data', '480Mbps'],
      ['Jacket', 'Nylon braid'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Length', options: ['1m', '2m', '3m'] },
    stock: 88,
  },
  {
    id: 'charger-20w-dual',
    name: '20W PD Dual-Port Wall Charger',
    brand: 'Goods2Hoods',
    category: 'charging',
    price: 229,
    rating: 4.7,
    reviews: 921,
    sold: 2180,
    image: '/images/charger.jpg',
    compat: 'SA 3-pin plug included',
    fits: ['*'],
    blurb: 'USB-C PD plus USB-A in one compact brick, with a proper South African plug in the box.',
    features: [
      '20W USB-C PD + 12W USB-A',
      'SANS 164-2 pin adapter',
      'Over-current protection',
      '18-month warranty',
    ],
    spec: [
      ['Output', '20W PD + 12W A'],
      ['Plug', 'SANS 164-2 included'],
      ['Protection', 'OCP / OVP / OTP'],
      ['Warranty', '18 months'],
    ],
    stock: 54,
  },
  {
    id: 'car-charger-36w',
    name: 'Retractable 36W Car Charger',
    brand: 'Goods2Hoods',
    category: 'charging',
    price: 189,
    rating: 4.3,
    reviews: 611,
    sold: 1340,
    image: '/images/charger.jpg',
    compat: '12V / 24V socket',
    fits: ['*'],
    blurb: 'A retractable USB-C lead that pulls out to 80cm and disappears when you park.',
    features: ['36W total output', '80cm retractable lead', 'Smart current limiter'],
    spec: [
      ['Output', '36W total'],
      ['Lead', '80cm retractable'],
      ['Socket', '12V / 24V'],
      ['Warranty', '12 months'],
    ],
    stock: 37,
  },
  {
    id: 'boost-10k',
    name: 'Boost 10 000mAh Power Bank',
    brand: 'Goods2Hoods',
    category: 'power',
    price: 199,
    was: 259,
    rating: 4.6,
    reviews: 4420,
    sold: 7310,
    image: '/images/powerbank.jpg',
    badge: 'Grid-free',
    compat: 'USB-C in/out + USB-A',
    fits: ['*'],
    blurb: 'Two and a half full charges per bank — the under-R200 pack that keeps selling out.',
    features: [
      '22.5W fast output',
      'USB-C in and out',
      'Four-LED charge gauge',
      'Clears a four-hour block twice over',
    ],
    spec: [
      ['Capacity', '10 000mAh'],
      ['Output', '22.5W'],
      ['Recharge', '3.5 hours'],
      ['Warranty', '12 months'],
    ],
    stock: 119,
  },
  {
    id: 'boost-20k',
    name: 'Boost 20 000mAh PD Power Bank',
    brand: 'Goods2Hoods',
    category: 'power',
    price: 429,
    rating: 4.8,
    reviews: 1890,
    sold: 2960,
    image: '/images/powerbank.jpg',
    badge: 'Grid-free',
    compat: 'Phone, tablet and router',
    fits: ['*'],
    blurb:
      'Enough capacity to keep the fibre router and two phones alive through a four-hour block.',
    features: [
      '22.5W + 20W PD dual output',
      'Runs a router via USB-C trigger',
      'Digital percentage display',
      'Recharges in 4.5 hours',
    ],
    spec: [
      ['Capacity', '20 000mAh'],
      ['Output', '22.5W + 20W PD'],
      ['Router runtime', '~5 hours'],
      ['Warranty', '12 months'],
    ],
    stock: 43,
  },
  {
    id: 'pocket-mag-5k',
    name: 'Pocket 5 000mAh Magnetic Pack',
    brand: 'Goods2Hoods',
    category: 'power',
    price: 249,
    rating: 4.4,
    reviews: 733,
    sold: 1620,
    image: '/images/powerbank.jpg',
    compat: 'MagSafe & magnetic cases',
    fits: ['iPhone 14 Pro', 'iPhone 15', 'iPhone 15 Pro', 'iPhone 16 Pro'],
    blurb: 'Snaps to the back of the phone and charges while you walk. No cable, no bulge.',
    features: ['15W magnetic wireless', 'Kickstand built in', 'Pass-through charging'],
    spec: [
      ['Capacity', '5 000mAh'],
      ['Wireless', '15W magnetic'],
      ['Extras', 'Fold-out kickstand'],
      ['Warranty', '12 months'],
    ],
    stock: 29,
  },
  {
    id: 'pulse-tws',
    name: 'Pulse TWS Earbuds',
    brand: 'Pulse Audio',
    category: 'audio',
    price: 299,
    was: 379,
    rating: 4.4,
    reviews: 6120,
    sold: 5840,
    image: '/images/earbuds.jpg',
    badge: 'Best seller',
    compat: 'Bluetooth 5.3',
    fits: ['*'],
    blurb: 'Four-mic ENC that genuinely cuts taxi noise on calls, with 30 hours in the case.',
    features: ['30h total battery', '4-mic ENC calling', 'IPX5 sweat resistant', 'USB-C quick charge'],
    spec: [
      ['Battery', '30h with case'],
      ['Mics', '4 x ENC'],
      ['Rating', 'IPX5'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Colour', options: ['Black', 'Bone', 'Amber'] },
    stock: 96,
  },
  {
    id: 'pulse-pro-anc',
    name: 'Pulse Pro ANC Earbuds',
    brand: 'Pulse Audio',
    category: 'audio',
    price: 479,
    rating: 4.6,
    reviews: 1204,
    sold: 1980,
    image: '/images/earbuds.jpg',
    compat: 'Bluetooth 5.3 multipoint',
    fits: ['*'],
    blurb: 'Real hybrid ANC at a price that still respects the budget.',
    features: ['-32dB hybrid ANC', 'Multipoint pairing', 'Low-latency game mode', 'Wireless case'],
    spec: [
      ['ANC', '-32dB hybrid'],
      ['Pairing', 'Multipoint'],
      ['Latency', '60ms game mode'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Colour', options: ['Black', 'Sand'] },
    stock: 34,
  },
  {
    id: 'beat-sport',
    name: 'Beat Buds Sport Hooks',
    brand: 'Pulse Audio',
    category: 'audio',
    price: 259,
    rating: 4.2,
    reviews: 887,
    sold: 1510,
    image: '/images/earbuds.jpg',
    compat: 'Bluetooth 5.2',
    fits: ['*'],
    blurb: 'Over-ear hooks that stay in through a full parkrun.',
    features: ['IPX6 rated', '9h per charge', 'Secure silicone hooks'],
    spec: [
      ['Battery', '9h per charge'],
      ['Rating', 'IPX6'],
      ['Fit', 'Over-ear hook'],
      ['Warranty', '12 months'],
    ],
    stock: 61,
  },
  {
    id: 'boom-mini',
    name: 'Boom Mini Bluetooth Speaker',
    brand: 'Pulse Audio',
    category: 'audio',
    price: 349,
    rating: 4.5,
    reviews: 1043,
    sold: 1720,
    image: '/images/speaker.jpg',
    compat: 'Bluetooth 5.3 + TWS',
    fits: ['*'],
    blurb: 'Pocket-sized, braai-loud, and pairs two units into stereo.',
    features: ['12h playtime', 'IPX7 waterproof', 'TWS stereo pairing', 'Carabiner strap'],
    spec: [
      ['Playtime', '12 hours'],
      ['Rating', 'IPX7'],
      ['Pairing', 'TWS stereo'],
      ['Warranty', '12 months'],
    ],
    stock: 40,
  },
  {
    id: 'work-light-1200',
    name: 'Grid-Free LED Work Light',
    brand: 'Grid-Free',
    category: 'loadshedding',
    price: 429,
    rating: 4.7,
    reviews: 2310,
    sold: 3480,
    image: '/images/light.jpg',
    badge: 'Grid-free',
    compat: 'USB-C rechargeable',
    fits: ['*'],
    blurb: '1200 lumens, magnetic base, and it doubles as a power bank when the block runs long.',
    features: [
      '1200lm across three modes',
      '8h runtime on low',
      'Magnet and hook mount',
      'Doubles as a 5 000mAh bank',
    ],
    spec: [
      ['Output', '1200 lumens'],
      ['Runtime', '8h on low'],
      ['Mount', 'Magnet + hook'],
      ['Warranty', '12 months'],
    ],
    stock: 52,
  },
  {
    id: 'rechargeable-bulb',
    name: 'Rechargeable 9W Bulb (2-pack)',
    brand: 'Grid-Free',
    category: 'loadshedding',
    price: 189,
    was: 239,
    rating: 4.5,
    reviews: 1760,
    sold: 4020,
    image: '/images/light.jpg',
    badge: 'Grid-free',
    compat: 'B22 bayonet & E27 screw',
    fits: ['*'],
    blurb: 'Screws into the fitting you already have and keeps glowing for four hours after the drop.',
    features: [
      '4h emergency runtime',
      'Auto-switch on outage',
      'B22 or E27 fitting',
      '6500K daylight',
    ],
    spec: [
      ['Runtime', '4 hours'],
      ['Fitting', 'B22 or E27'],
      ['Colour', '6500K daylight'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Fitting', options: ['B22 bayonet', 'E27 screw'] },
    stock: 134,
  },
  {
    id: 'loadshed-kit',
    name: 'Grid-Free Survival Kit',
    brand: 'Grid-Free',
    category: 'loadshedding',
    price: 499,
    was: 617,
    rating: 4.8,
    reviews: 940,
    sold: 2140,
    image: '/images/light.jpg',
    badge: 'Bundle',
    compat: 'Everything USB-C',
    fits: ['*'],
    blurb: 'Power bank, work light and a 3-in-1 cable in one box. Sorted before the next block.',
    features: [
      'Boost 10 000mAh bank',
      'Grid-Free work light',
      '3-in-1 fast cable',
      'Save R118 on the set',
    ],
    spec: [
      ['Contents', 'Bank + light + cable'],
      ['Saving', 'R118'],
      ['Ships as', 'One parcel'],
      ['Warranty', '12 months'],
    ],
    stock: 26,
  },
  {
    id: 'trigger-buttons',
    name: 'L1R1 Trigger Buttons',
    brand: 'Street Series',
    category: 'gaming',
    price: 99,
    rating: 4.3,
    reviews: 2870,
    sold: 3960,
    image: '/images/gaming.jpg',
    badge: 'Best seller',
    compat: 'Phones 60–90mm wide',
    fits: ['*'],
    blurb: 'Metal-contact triggers with a crisp actuation for shooters. No battery required.',
    features: ['Zero-latency capacitive contact', 'Fits cased phones', 'Non-slip clamp pads'],
    spec: [
      ['Type', 'Capacitive contact'],
      ['Fit', '60–90mm wide'],
      ['Power', 'None required'],
      ['Warranty', '12 months'],
    ],
    stock: 178,
  },
  {
    id: 'cooling-fan',
    name: 'Semiconductor Cooling Fan',
    brand: 'Street Series',
    category: 'gaming',
    price: 199,
    rating: 4.4,
    reviews: 1330,
    sold: 2280,
    image: '/images/gaming.jpg',
    compat: 'Universal clamp + magnetic',
    fits: ['*'],
    blurb: 'Drops surface temperature so the frame rate holds past round three.',
    features: ['Peltier cooling plate', 'Drops up to 18°C', 'RGB ring with an off mode', 'USB-C powered'],
    spec: [
      ['Cooling', 'Peltier plate'],
      ['Delta', 'Up to 18°C'],
      ['Power', 'USB-C'],
      ['Warranty', '12 months'],
    ],
    stock: 47,
  },
  {
    id: 'ergo-grip',
    name: 'Ergo Gaming Grip + Stand',
    brand: 'Street Series',
    category: 'gaming',
    price: 179,
    rating: 4.2,
    reviews: 604,
    sold: 1120,
    image: '/images/gaming.jpg',
    compat: 'Phones up to 6.9 inch',
    fits: ['*'],
    blurb: 'Console-style grips that fold flat into a desk stand between matches.',
    features: ['Folding dual grip', 'Cable pass-through', 'Rubberised clamp'],
    spec: [
      ['Fit', 'Up to 6.9 inch'],
      ['Folds', 'Into a desk stand'],
      ['Clamp', 'Rubberised'],
      ['Warranty', '12 months'],
    ],
    stock: 58,
  },
  {
    id: 'vent-mount',
    name: 'Nu-Fold Magnetic Vent Mount',
    brand: 'Goods2Hoods',
    category: 'car',
    price: 159,
    was: 199,
    rating: 4.6,
    reviews: 3410,
    sold: 4560,
    image: '/images/carmount.jpg',
    badge: 'Best seller',
    compat: 'All vent types + MagSafe',
    fits: ['*'],
    blurb: 'Folds into a coin-sized puck and holds a 6.9 inch phone through a Joburg pothole.',
    features: ['N52 magnet array', 'Folds flat for a pocket', 'Vent-blade safe clamp', 'Metal plate included'],
    spec: [
      ['Magnets', 'N52 array'],
      ['Folded size', 'Coin-sized puck'],
      ['Fit', 'All vent blade types'],
      ['Warranty', '12 months'],
    ],
    stock: 83,
  },
  {
    id: 'dash-mount-xl',
    name: 'Dash Suction Mount XL',
    brand: 'Goods2Hoods',
    category: 'car',
    price: 199,
    rating: 4.3,
    reviews: 712,
    sold: 1290,
    image: '/images/carmount.jpg',
    compat: 'Windscreen & dashboard',
    fits: ['*'],
    blurb: 'A gel suction cup with a telescopic arm that survives a summer parked in the sun.',
    features: ['Heat-stable gel cup', '18cm telescopic arm', 'One-hand clamp release'],
    spec: [
      ['Cup', 'Heat-stable gel'],
      ['Arm', '18cm telescopic'],
      ['Release', 'One-handed'],
      ['Warranty', '12 months'],
    ],
    stock: 36,
  },
  {
    id: 'desk-stand',
    name: 'Fold Aluminium Desk Stand',
    brand: 'Goods2Hoods',
    category: 'car',
    price: 149,
    rating: 4.7,
    reviews: 1980,
    sold: 2740,
    image: '/images/stand.jpg',
    compat: 'Phones & tablets to 11 inch',
    fits: ['*'],
    blurb: 'The folding stand format that moves 8 456 units a month, in brushed aluminium.',
    features: ['Anodised aluminium', 'Folds to 9mm thick', 'Adjustable viewing angle', 'Silicone pads'],
    spec: [
      ['Material', 'Anodised aluminium'],
      ['Folded', '9mm thick'],
      ['Fit', 'Up to 11 inch'],
      ['Warranty', '12 months'],
    ],
    variants: { label: 'Finish', options: ['Graphite', 'Silver'] },
    stock: 71,
  },
]

export const getProduct = (id: string) => products.find((p) => p.id === id)

export const categoryName = (id: CategoryId) =>
  categories.find((c) => c.id === id)?.name ?? id

export const isUniversal = (product: Product) => product.fits[0] === '*'

export const fitsDevice = (product: Product, model: string | null) => {
  if (!model) return true
  if (isUniversal(product)) return true
  return product.fits.includes(model)
}

/** Exact-fit items first, then universal, then by volume. */
export const forDevice = (model: string) =>
  products
    .filter((p) => fitsDevice(p, model))
    .sort((a, b) => {
      const rank = (p: Product) => (isUniversal(p) ? 1 : 0)
      return rank(a) - rank(b) || b.sold - a.sold
    })

export const relatedTo = (product: Product, count = 4) =>
  products
    .filter((p) => p.id !== product.id)
    .sort((a, b) => {
      const same = (p: Product) => (p.category === product.category ? 0 : 1)
      return same(a) - same(b) || b.sold - a.sold
    })
    .slice(0, count)
